routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/home', 'ContactController@index')->name('contact');



Route::resource('products' ,'ProductController');
Route::resource('categories' ,'CategorieController');

app/Categorie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorie extends Model
{
    protected $guarded=[];
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded=[];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategorieController.php
<?php

namespace App\Http\Controllers;
use App\Categorie;
use Illuminate\Http\Request;

class CategorieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories= Categorie::all();
        return view('categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData=$request->validate([
            'name'=>'required|max:150|min:3'
        ]);
        //save dataBase |ORM
        $categorie=Categorie::create($validatedData);
        //redirection to/categorie page
        return redirect('/categories')->with('success','Categorie added successfully...');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Categorie $categorie)
    {
        return view('categories.show',compact('categorie'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Categorie $categorie)
    {
        return view('categories.edit',compact('categorie'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categorie $categorie)
    {

        $validatedData=$request->validate([
            'name'=>'required|max:150|min:3'
        ]);
        $categorie->update($validatedData);
        return redirect('/categories')->with('success','Categorie update successfully ...');;

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categorie $categorie)
    {
        $categorie->delete();
        return redirect('/categories')->with('success','Ctegories deleted successfully ...');;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
 /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products= Product::all();
        return view('products.index',compact('products'));
    }

    public function create()
    {
        return view('products.create');
    }

      /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $validatedData=$request->validate([
            'name'=>'required|max:15|min:3',
            'price'=>'required',
            'description'=>'required',
            'expirationDate'=>'required'
        ]);
        //save dataBase |ORM
        $product=Product::create($validatedData);
        //redirection to/products page
        return redirect('/products')->with('success','Product added successfully...');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show',compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit',compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Product $product )
    {
        $validatedData=$request->validate([
            'name'=>'required|max:255|min:3',
            'price'=>'required',
            'description'=>'required',
            'expirationDate'=>'required'
        ]);
        $product->update($validatedData);
        return redirect('/products')->with('success','Product upded successfully ...');;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return redirect('/products')->with('success','Product deleted successfully ...');;
    }
}

resources/views/categories/create.blade.php
@extends('layouts/master')


@section('title')
<h1>Ajoute une Categorie</h1>
@endsection

@section('content')


<form method="POST" action="{{ route('categories.store')}}">
    @csrf

    <legend>Ajoute une Categorie</legend>

    <div class="form-group">
        <label for="name">Nom Categorie</label>
        <input type="text" class="form-control @error('name') is-invalid @enderror"  name="name" >
        @error('name')
        <span class="invalid-feedback" role="alert">
            <strong>{{$message}}</strong>
        </span>
        @enderror
      </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
  </form>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts/master')


@section('title')
Modifier une Categorie
@endsection

@section('content')
<h1>Modifier une Categorie</h1>


<form method="POST" action="{{ route('categories.update',$categorie->id)}}">

    @csrf
    @method('PATCH')
    
    <legend>Ajoute une Categorie</legend>

    <div class="form-group">
        <label for="name">Nom Categorie</label>
        <input type="text" class="form-control"  name="name"  value="{{$categorie->name}}">
      </div>
    <button type="submit" class="btn btn-primary">Update</button>
  </form>


@endsection

resources/views/categories/index.blade.php
@extends('layouts/master')

@section('title')
liste des Categorie
@endsection

@section('content')
<h1>liste des Categorie</h1>



@if (session()->get('success'))
    <div class="alert alert-success" role="alert">
    {{ session()->get('success') }}
    </div>
@endif

<table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($categories as $item)
            <tr>
                <td>{{$item->name}}</td>
                <td><a href="{{route('categories.show',$item->id)}}" class="btn btn-sm btn-warning">Consulter</a></td>
                <td><a href="{{route('categories.edit',$item->id)}}" class="btn btn-sm btn-success">Edite</a></td>
                <td>
                    <form action="{{route('categories.destroy',$item->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
  </table>
  <a href="{{route('categories.create')}}" class="btn btn-info">New category</a>
@endsection

resources/views/categories/show.blade.php
@extends('layouts/master')

@section('title')
Show Categorie
@endsection

@section('content')
<h1>show categories</h1>
<div class="card-deck">
    <div class="card">
      <img src="https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">this car {{ $categorie->name }}</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
    <div class="card">
      <img src="https://images.unsplash.com/photo-1551727324-355cda9f1884?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ $categorie->name }}</h5>
        <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
    <div class="card">
      <img src="https://images.unsplash.com/photo-1560253787-9c3babc1fab2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ $categorie->name }}</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>@yield('title')</title>
  </head>
  <body>
    @yield('content')
    @yield('css')


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    @yield('js')
  </body>
</html>

resources/views/products/create.blade.php
@extends('layouts/master')


@section('title')
<h1>create new product</h1>
@endsection

@section('content')
Ajout nouveau produit
<form method="POST" action="{{ route('products.store')}}">
    @csrf
  <fieldset>
    <legend>create new product</legend>

    <div class="form-group">
      <label for="name">Nom</label>
      <input type="text" class="form-control @error('name') is-invalid @enderror"  name="name" >
      @error('name')
      <span class="invalid-feedback" role="alert">
          <strong>{{$message}}</strong>
      </span>
      @enderror
    </div>


    <div class="form-group">
      <label for="Prix">Prix</label>
      <input type="Number" class="form-control @error('price') is-invalid @enderror" name="price" >
      @error('price')
      <span class="invalid-feedback" role="alert">
          <strong>{{$message}}</strong>
      </span>
      @enderror
    </div>

    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control @error('description')  is-invalid @enderror" name="description" rows="3"></textarea>
      @error('description')
      <span class="invalid-feedback" role="alert">
          <strong>{{$message}}</strong>
      </span>
      @enderror
    </div>

      <div class="form-group">
        <label for="expirationDate">expirationDate</label>
        <input type="date" class="form-control @error('expirationDate')  is-invalid @enderror" name="expirationDate" placeholder="expirationDate">
        @error('expirationDate')
      <span class="invalid-feedback" role="alert">
          <strong>{{$message}}</strong>
      </span>
      @enderror
      </div>

    <button class="btn btn-primary" type="submit">Envoyer</button>
  </fieldset>
</form>

@endsection

resources/views/products/edit.blade.php
@extends('layouts/master')


@section('title')
edit product
@endsection

@section('content')
<h1>edit product</h1>



<form method="POST" action="{{ route('products.update',$product->id)}}">
    @csrf
    @method('PATCH')
  <fieldset>
    <legend>create new product</legend>

    <div class="form-group">
      <label for="name">Nom</label>
      <input type="text" class="form-control" name="name" value="{{$product->name}}">
    </div>


    <div class="form-group">
      <label for="Prix">Prix</label>
      <input type="Number" class="form-control" name="price" value="{{$product->price}}">
    </div>

    <div class="form-group">
      <label for="description">Description</label>
      <textarea class="form-control" name="description" rows="3">{{$product->description}}</textarea>
    </div>

      <div class="form-group">
        <label for="expirationDate">expirationDate</label>
        <input type="date" class="form-control" name="expirationDate" value="{{$product->expirationDate}}">
      </div>

    <button class="btn btn-primary" type="submit">Update</button>
  </fieldset>
</form>

@endsection

resources/views/products/index.blade.php
@extends('layouts/master')

@section('title')
list produit
@endsection

@section('content')
<h1>list products</h1>
<a href="{{route('products.create')}}" class="btn btn-success">New product</a>

@if (session()->get('success'))
    <div class="alert alert-success" role="alert">
    {{ session()->get('success') }}
    </div>
@endif


<h1>khalil</h1>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Price</th>
        <th scope="col">expirationDate</th>
        <th scope="col">Actions</th>
        <th scope="col">Edite</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($products as $item)
            <tr>
                <td>{{$item->name}}</td>
                <td>{{$item->price}}</td>
                <td>{{$item->expirationDate}}</td>
                <td><a href="{{route('products.show',$item->id)}}" class="btn btn-sm btn-warning">Consulter</a></td>
                <td><a href="{{route('products.edit',$item->id)}}" class="btn btn-sm btn-warning">Edite</a></td>
                <td>
                    <form action="{{route('products.destroy',$item->id)}}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
  </table>
  @endsection

resources/views/products/show.blade.php
@extends('layouts/master')

@section('title')
Show products
@endsection

@section('content')
<h1>show products</h1>
<div classe="contrainer">
    <div class="card" style="width: 18rem;">
        <img src="https://images.unsplash.com/photo-1479894720049-067d8b87f2d9?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ $product->name }}</h5>
          <h6>{{ $product->price }} TND</h6>
          <p class="card-text">{{ $product->description }}</p>
          <a href="{{route('products.edit',$product->id)}}" class="btn btn-primary">Edite</a>
        </div>
      </div>
</div>
@endsection